---
    - name: system update
      yum:
        name: "*"
        state: latest

    - name: install required packages for docker
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: add docker-ce repo
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    
    - name: install docker packages
      yum:
        name: "{{ packages }}"
      vars: 
        packages:
        - docker-ce
        - docker-ce-cli

    - name: create 'docker' group
      group:
        name: docker
        state: present

    - name: create 'docker' user
      user:
        name: docker
        group: docker

    - name: create directories for insecure registry files
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /etc/docker
        - /etc/containers

    - name: add CIDR for insecure registry
      blockinfile:
        path: /etc/containers/registries.conf
        block: |
          [registries.insecure]
          registries = ['172.30.0.0/16']

    - name: create daemon.json file for insecure registry
      blockinfile:
        path: /etc/docker/daemon.json
        block: |
          {
              "insecure-registries": [
                "172.30.0.0/16"
              ]
          }

    - name: reload the docker daemon and restart
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker
        enabled: yes

    - name: enable IP forward and update the sysctl
      command: echo "net.ipv4.ip_forward = 1" | sudo tee -a /etc/sysctl.conf && sysctl -p

    - name: disable firewalld service
      systemd:
        state: stopped
        name: firewalld

    - name: download openshift archive and prepare
      get_url:
        url: https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
        dest: /root/
    - name: tar
      unarchive:
        src: /root/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
        dest: /root/
    - name: mv
      command: mv /root/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/kubectl /root/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc /bin/     
   
    - name: cluster up
      command: oc cluster up --public-hostname=18.191.188.16
