---
    - name: create private registry user and install docker-py
      shell: "{{ item }}"
      with_items:
        - docker run --entrypoint htpasswd registry -Bbn deniz 123123 > /root/auth/htpasswd
        - pip install docker-py

    - name: pull the registry image
      docker_image:
        name: registry

    - name: create registry container with port 5000
      docker_container:
        name: registryv2
        image: registry
        ports: "5000:5000"
        detach: yes
        
